### ISSUE TITLE
Default Mapbox GL font is missing 

### ISSUE THREAD

**Issue by rinigus** [otsaloma/cartago-styles#1]
When you create a new POI object on a map within the application, the default fonts are used by Mapbox GL, unless you specify them. If the application is developed against only one provider, we can find which font to use and specify it in the app. However, issues appear as soon as you start developing against multiple basemaps and allow users to swap them. To avoid the issues, we need to either add default fonts (https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-font, ["Open Sans Regular","Arial Unicode MS Regular"]) or let the server to supply some alternative. In OSM Scout Server, I am providing Open Sans Regular and backing it with Noto fonts. How to do it exactly with the tileserver, I don't know. In particular, I don't know whether requested URL that comes in form 

... Open Sans Regular,Arial Unicode MS Regular ...

is split into parts and whether tileserver searches for each of the fonts separately. From that it will depend on how to add the default font to the server.

**Comment by otsaloma** [comment]
Sorry, I still don't understand this – what does "When you create a new POI object on a map within the application" mean?

**Comment by rinigus** [comment]
Sorry, I was not clear then probably.

When you use Mapbox GL, you draw the map and can insert your objects into it. For example, we can add POIs with the labels as a result of the search. They all get nicely integrated into the map and between the layers if you wish.

An examples of such addition are https://github.com/rinigus/mapbox-gl-qml/blob/master/app/qml/main.qml#L191 (where the font is specified at line 226) and https://github.com/rinigus/poor-maps/blob/gl/qml/Map.qml#L447 where the default font is used (no `text-font` is given).

Its easier not to specify font and rely on the default of the library. That way we can assume that all map providers would do something in response to such request and you can switch between basemaps if you wish. However, in case of Cartago, the default is not served, unfortunately.

**Comment by otsaloma** [comment]
Ah, OK, so there's no fallback like "sans-serif" in CSS? Seems a bit silly to have to bundle a particular font. Does the default font actually need to be provided or just the name, i.e. can it just be a symlink to Noto or a copy of Noto?

**Comment by rinigus** [comment]
Symlink should work, I think . In general, font handling by Mapbox GL is rather complicated since OpenGL doesn't support fonts as such.

Depending on how tileserver handles the requests , we may have to name default font symlink by the name of one font or the pair.

I'll submit combined Noto font as PR and then we could try to link it there.

**Comment by otsaloma** [comment]
Possibly related: https://github.com/klokantech/tileserver-gl/commit/734d1f01f0b6d128e89382c9d47b639e056a6176

**Comment by rinigus** [comment]
I think this commit works through the fallback fonts as given in the list, although they seem to prioritize Noto. Not sure it will work if the given list is  Open Sans Regular,Arial Unicode MS Regular. 

Can we try to put symlink to Open Sans Regular -> Noto Sans Regular and see if it works?

I can also submit Open Sans fonts, but they cover rather small range though.

**Comment by otsaloma** [comment]
There are now symlinks on the server `Open Sans {Regular,Bold,Italic}` to `Noto Sans {Regular,Bold,Italic}`.

**Comment by rinigus** [comment]
Just tested and it looks like its insufficient - Poor Maps GL still complains that the corresponding default font is missing when I try to add a POI. 

I suspect that the server looks for a folder called

`Open Sans Regular,Arial Unicode MS Regular`

as the name of the font is in the Mapbox GL terminology. Namely, its considered that the combined font is generated with the fallback as given in the name before you roll out the service, it's usually not generated on fly. I implemented on-fly generation for OSM Scout Server, but that also has some limitations. 

You probably could see in your logs that some font was requested and it was missing. 

I would suggest to make a symbolic link from `Open Sans Regular,Arial Unicode MS Regular` to Noto Sans Regular and then I can try again.

If you wish to try yourself, the code is at https://github.com/rinigus/poor-maps/tree/gl and just try to add a POI by holding your finger for some time on a map, as in Poor Maps proper (just more time is needed, it seems).

**Comment by otsaloma** [comment]
Indeed:

```
GET /fonts/Open%20Sans%20Regular,Arial%20Unicode%20MS%20Regular/0-255.pbf?apikey=[...] 400 35 - 2.564 ms
```

I don't have time to test now, but I added those symlinks.

```
drwxr-xr-x 2 www www 12288 Dec 16 17:46 Noto Sans Bold
drwxr-xr-x 2 www www  4096 Dec 14 21:00 Noto Sans Italic
drwxr-xr-x 2 www www 12288 Dec 14 21:00 Noto Sans Regular
lrwxrwxrwx 1 www www    14 Dec 16 16:30 Open Sans Bold -> Noto Sans Bold
lrwxrwxrwx 1 www www    14 Dec 16 17:46 Open Sans Bold,Arial Unicode MS Bold -> Noto Sans Bold
lrwxrwxrwx 1 www www    16 Dec 16 16:30 Open Sans Italic -> Noto Sans Italic
lrwxrwxrwx 1 www www    16 Dec 16 17:46 Open Sans Italic,Arial Unicode MS Italic -> Noto Sans Italic
lrwxrwxrwx 1 www www    17 Dec 16 16:30 Open Sans Regular -> Noto Sans Regular
lrwxrwxrwx 1 www www    17 Dec 16 17:49 Open Sans Regular,Arial Unicode MS Regular -> Noto Sans Regular
```

**Comment by rinigus** [comment]
Hi! Something is still wrong and I cannot get the Open Sans Regular,Arial Unicode MS Regular font. Looks like all fonts are requested with the API key, so its not a problem with that. I presume that you will see my latest attempts in the logs as well.

I don't know how the tileserver is handling font requests, maybe there is some problem there. When I tried to access Open Sans Bold there was no luck either. Maybe it doesn't line symlinks? Would be strange though...

**Comment by otsaloma** [comment]
Should work now, I think. Seems Tileserver GL by default only serves fonts actually used by an included style. There's an API endpoint and all fonts seem listed now: <http://tile.cartago.io/fonts.json?apikey=XXX>

**Comment by rinigus** [comment]
It works now! Thank you very much!
