### ISSUE TITLE
Missing icons, probably POI3

### ISSUE THREAD

**Issue by rinigus** [otsaloma/cartago-styles#3]
When working on native Mapbox GL client, I observed that labels disappear at higher zooms at Cartago. Later I found the same when working on OSM Scout Server. Turned out that some icons were missing in the sprite leading to such bug in Mapbox GL Native. While this bug/feature has been fixed in 1.2.0 version of Mapbox GL Qt bindings (can't use them yet due to other issues), it highlights that some icons are missing. For now, I fixed it in OSM Scout Server by limiting POI ranks ( https://github.com/rinigus/osmscout-server/blob/master/styles/mapboxgl/styles/osmbright.json#L3735 ). But, I guess, we better find what's missing.

**Comment by otsaloma** [comment]
I haven't noticed this. Is this limited to your SFOS port of Mapbox GL or visible in the [Cartago web demos](http://cartago.io/maps/) as well?

**Comment by rinigus** [comment]
Its actually visible on any Mapbox GL Native (or was visible until the fix in autumn, I think). Mapbox GL JS, as used on web demos, ignores the error and continues to draw. Hence you don't see it on web demo. I could see it on SFOS and Linux PC when using C++ library.

I filed an issue on how to get the missing sprite, no reply to it yet from Mapbox GL. As soon as I get the response on how to debug it, I'll let you know. 

In my case, I am sure the problem of missing icons is coming from the fact that the class is not defined for all possible imports and I am hitting ELSE statement in SQL:

 https://github.com/rinigus/mapbox-gl-importer/blob/master/layers/poi/update.sql#L66

for some cases as specified in the import mappings:

https://github.com/rinigus/mapbox-gl-importer/blob/master/layers/poi/mapping.yaml

As these scripts are similar or same as used by OpenMapTiles, I expect to have the same issue with Cartago. For OSM Scout Server, I am going to go through import again and will fix such cases. 

I just wanted to file all I have learned during my recent work to be sure that I didn't forget anything important.

**Comment by rinigus** [comment]
For OSM Scout Server tiles, I have altered the schema and have rather strict control on what is requested from the style in form of an icon (field `symbol`) and limited set of class field values. For POI, definitions are at https://github.com/rinigus/mapbox-gl-importer/tree/master/layers/poi . 

As for the original issue, I don't there is much that can be done without running all these queries against planet PostGIS and examine what comes out. So, for OpenMapTiles, it will be hard to address it properly and give the list of all possible POI3 icons. In addition, such list may change in future. 

Fortunately, it is expected that later versions of Mapbox GL Native will be addressing missing icons the same way as Mapbox GL JS - simply ignoring it - and rendering the rest of the layers.

I would suggest to close the issue for now. It has served it purpose in terms of documenting it.

**Comment by otsaloma** [comment]
OK, thanks, let's just wait it out.
